name: inactivity_detector
description: "A widget that detects user inactivity and triggers callbacks after a specified duration."
version: 0.0.2
homepage: https://github.com/faishallogique/inactivity-detector

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0